### ISSUE TITLE
cannot add pun_sensor.mono_orario as Ingress Entity

### ISSUE THREAD

**Issue by giosooul** [virtualdj/pun_sensor#1]
Cannot find **pun_sensor.*** in the list of sensor for Helpers of "Entity for current price". It seems that entities don't have a unique_ID.

**Comment by virtualdj** [comment]
They (originally) didn't have an `unique_id` because I didn't find a way to "lock" the `entity_id` to something that could be linked to the word "pun" if that word wasn't present in the sensor name.

After your comment, I tried again and eventually I was able to do it in commit 30df68f.

![entity-id now has a fixed (but user-changeable) name](https://user-images.githubusercontent.com/3251704/219870593-bd59e807-99ea-4d41-9614-b88528c95244.png)

There's a catch, though. **Sensors have been renamed** from the previous version:
| Old sensor name | New sensor name (ver. >= 0.2.4) |
| --- | --- |
| pun_sensor.fascia_corrente | sensor.pun_fascia_corrente |
| pun_sensor.prezzo_fascia_corrente | sensor.pun_prezzo_fascia_corrente |
| pun_sensor.fascia_f1 | sensor.pun_fascia_f1 |
| pun_sensor.fascia_f2 | sensor.pun_fascia_f2 |
| pun_sensor.fascia_f3 | sensor.pun_fascia_f3 |
| pun_sensor.mono_orario | sensor.pun_mono_orario |

**Comment by giosooul** [comment]
Thank you @virtualdj I'll try it. In the meantime I tried a fast workaround replacing the entity_id with **unique_id** in defs:

```
    @property
    def unique_id(self) -> str:
        """Restituisce l'entity id del sensore"""
        if (self.tipo == PUN_FASCIA_F3):
            return DOMAIN + ".fascia_f3"
        elif (self.tipo == PUN_FASCIA_F2):
            return DOMAIN + ".fascia_f2"
        elif (self.tipo == PUN_FASCIA_F1):
            return DOMAIN + ".fascia_f1"
        elif (self.tipo == PUN_FASCIA_MONO):
            return DOMAIN + ".mono_orario"
        else:
            return None
```

and I was able to see them as entities!

![image](https://user-images.githubusercontent.com/32428029/219871455-ea8b65cb-c51f-4fed-a3e0-a18c4416f931.png)

I have tried it successfully this morning...I will check your code.

Thank you again,
Gio

**Comment by virtualdj** [comment]
Yeah, of course it works like so but if you check the "real" `entity_id` that appears in Lovelace UI you will see that it's difficult to identify that this sensor is coming from this integration.
With the latest commit it should be much better... I would have done it in the first release, if only HA better explains these "quircks"!
